spring:
  application:
    name: rostelecom-tms

  datasource:
    url: jdbc:postgresql://localhost:5432/tms
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:database/changelog/db.changelog-master.xml